### ISSUE TITLE
Unable to retrieve endpoint information from: https://control.cloud-object-storage.cloud.ibm.com/v2/endpoints

### ISSUE THREAD

**Issue by VidyasagarMSC** [ibm-messaging/kafka-connect-ibmcos-sink#13] opened 2021-01-22 08:47 UTC
Following the steps mentioned [here](https://cloud.ibm.com/docs/EventStreams?topic=EventStreams-cos_connector), I am trying to start the COS Sink Connector to archive data from Kafka topics in Event Streams to an instance of the Cloud Object Storage service.

I created a Kubernetes cluster on VPC Gen 2 to run the connector and blocked with the error while running the Kafka Connect COS sink. This is when I access http://localhost:8083/connectors/cos-sink/status

```
{
    "name": "cos-sink",
    "connector": {
        "state": "RUNNING",
        "worker_id": "172.17.59.85:8083"
    },
    "tasks": [{
        "id": 0,
        "state": "FAILED",
        "worker_id": "172.17.29.72:8083",
        "trace": "com.ibm.cos.ClientFactoryException: java.io.IOException: Unable to retrieve endpoint information from: https://control.cloud-object-storage.cloud.ibm.com/v2/endpoints\n\tat com.ibm.cos.ClientFactoryImpl.newClient(ClientFactoryImpl.java:42)\n\tat com.ibm.eventstreams.connect.cossink.COSSinkTask.start(COSSinkTask.java:104)\n\tat org.apache.kafka.connect.runtime.WorkerSinkTask.initializeAndStart(WorkerSinkTask.java:300)\n\tat org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:189)\n\tat org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:175)\n\tat org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:219)\n\tat java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:522)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:277)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)\n\tat java.lang.Thread.run(Thread.java:822)\nCaused by: java.io.IOException: Unable to retrieve endpoint information from: https://control.cloud-object-storage.cloud.ibm.com/v2/endpoints\n\tat com.ibm.cos.endpoints.Endpoints.fetch(Endpoints.java:78)\n\tat com.ibm.cos.ClientFactoryImpl.newClient(ClientFactoryImpl.java:39)\n\t... 10 more\n"
    }],
    "type": "sink"
}
```

Any one has seen this issue and found a solution?

**Comment by VidyasagarMSC** [comment] 2021-01-22 08:48
Tried on Kubernetes -Classic to see the same result. Also, I am able to curl the endpoint https://control.cloud-object-storage.cloud.ibm.com/v2/endpoints from inside the container

**Comment by l2fprod** [comment] 2021-01-22 16:12
Looks like a duplicate of #12

**Comment by mimaison** [comment] 2021-01-22 16:56
DUP of #12, closing

**Closed by mimaison** 2021-01-22 16:56 UTC
